"""added milestone and goals table

Revision ID: 775c283c1dae
Revises: 9d27d9870915
Create Date: 2026-08-15 20:05:59.624322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775c283c1dae'
down_revision: Union[str, Sequence[str], None] = '9d27d9870915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('goals', sa.Column('title', sa.String(), nullable=False))
    op.add_column('goals', sa.Column('target_date', sa.DateTime(), nullable=True))
    op.add_column('goals', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'goals', 'users', ['user_id'], ['id'])
    op.add_column('milestones', sa.Column('goal_id', sa.Integer(), nullable=False))
    op.add_column('milestones', sa.Column('title', sa.String(), nullable=False))
    op.add_column('milestones', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('milestones', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_milestones_goal_id'), 'milestones', ['goal_id'], unique=False)
    op.create_index(op.f('ix_milestones_id'), 'milestones', ['id'], unique=False)
    op.create_foreign_key(None, 'milestones', 'goals', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'milestones', type_='foreignkey')
    op.drop_index(op.f('ix_milestones_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_goal_id'), table_name='milestones')
    op.drop_column('milestones', 'time_created')
    op.drop_column('milestones', 'completed')
    op.drop_column('milestones', 'title')
    op.drop_column('milestones', 'goal_id')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_column('goals', 'time_created')
    op.drop_column('goals', 'target_date')
    op.drop_column('goals', 'title')
    op.drop_column('goals', 'user_id')
    # ### end Alembic commands ###
