"""add entry table

Revision ID: 9d27d9870915
Revises: b87955d22452
Create Date: 2026-08-15 09:00:43.335125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d27d9870915'
down_revision: Union[str, Sequence[str], None] = 'b87955d22452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('entries', sa.Column('content', sa.String(), nullable=False))
    op.add_column('entries', sa.Column('mood', sa.String(), nullable=True))
    op.add_column('entries', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_entries_id'), 'entries', ['id'], unique=False)
    op.create_index(op.f('ix_entries_user_id'), 'entries', ['user_id'], unique=False)
    op.create_foreign_key(None, 'entries', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_index(op.f('ix_entries_user_id'), table_name='entries')
    op.drop_index(op.f('ix_entries_id'), table_name='entries')
    op.drop_column('entries', 'time_created')
    op.drop_column('entries', 'mood')
    op.drop_column('entries', 'content')
    op.drop_column('entries', 'user_id')
    # ### end Alembic commands ###
